spring:
  application:
    name: workshop-server
  profiles:
    default: dev
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080
