spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/workshop}
    username: ${DB_USER:workshop}
    password: ${DB_PASSWORD:1111}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: info

app:
  auth:
    accounts:
      - username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:admin1234}
        role: ADMIN
      - username: ${PARTICIPANT_USERNAME:user01}
        password: ${PARTICIPANT_PASSWORD:user1234}
        role: PARTICIPANT
